name: Build RustDesk Windows (Flutter Only)

on:
  workflow_dispatch:   # 手动触发

jobs:
  build-windows-flutter:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.24.0"   # 建议跟 rustdesk 上游版本保持一致

      - name: Enable Windows Desktop
        run: |
          flutter config --enable-windows-desktop
          flutter doctor -v

      - name: Install dependencies
        run: |
          choco install -y cmake
          choco install -y ninja
          choco install -y llvm

      - name: Generate flutter_rust_bridge code
        run: |
          cargo install flutter_rust_bridge_codegen --version 1.75.3 --features uuid
          flutter pub get
          flutter_rust_bridge_codegen --rust-input src/flutter_ffi.rs --dart-output flutter/lib/generated_bridge.dart

      - name: Build Windows Release
        run: |
          python build.py --flutter
          flutter build windows --release

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-flutter
          path: flutter/build/windows/runner/Release
