name: Build RustDesk Windows (Flutter Only)

on:
  workflow_dispatch:

jobs:
  generate-bridge:
    uses: ./.github/workflows/bridge.yml

  build-RustDeskTempTopMostWindow:
    uses: ./.github/workflows/third-party-RustDeskTempTopMostWindow.yml
    with:
      upload-artifact: true
      target: windows-2022
      configuration: Release
      platform: x64
      target_version: Windows10

  build-for-windows-flutter:
    runs-on: windows-2022
    needs: [build-RustDeskTempTopMostWindow, generate-bridge]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/download-artifact@v4
        with:
          name: bridge-artifact
          path: ./

      - uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15.0.6"

      - uses: subosito/flutter-action@v2.12.0
        with:
          channel: "stable"
          flutter-version: "3.24.5"

      - name: Build rustdesk
        run: |
          python3 .\build.py --portable --hwcodec --flutter --vram --skip-portable-pack

      - name: Upload Release folder
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-release
          path: flutter/build/windows/x64/runner/Release
